### ISSUE TITLE
Should everyone be allowed to call Notify on IPublisher?

### ISSUE THREAD

**Issue by m-wilczynski** [Trooper13/ObserverPattern#2]
**Problem**
Currently anyone can call `IPublisher.Notify`, since it's a public method defined on `IPublisher`.
Let's take `Shop` implementation - should anyone besides Shop be allowed, to notify when products list changes?
If no, then perhaps we have encapsulation issue here?

**Action points:**

- [x] fix encapsulation issues in `IPublisher` design

**Comment by Trooper13** [comment]
Is it possible to make IPublisher method private? Interfaces are public by design.

**Comment by m-wilczynski** [comment]
Correct - interfaces are public by design, therefore any of their definitions (methods, properties) will be public too.
However, you should consider interface as a public contract of what we allow from "outside" of our class, not what can be implemented in derived class per se.

Let me give you an example.
What will happen, if I remove:
https://github.com/Trooper13/ObserverPattern/blob/442af218d9a38b686edf517d1528457a9e752812/src/Observer/Publisher/IPublisher.cs#L10
and change access modifier in implementation to `private`:
https://github.com/Trooper13/ObserverPattern/blob/442af218d9a38b686edf517d1528457a9e752812/src/Observer/Shop.cs#L49

Answer is: nothing, since only Shop.cs should access its own `Notify` method:
https://github.com/Trooper13/ObserverPattern/blob/442af218d9a38b686edf517d1528457a9e752812/src/Observer/Shop.cs#L20-L25
https://github.com/Trooper13/ObserverPattern/blob/442af218d9a38b686edf517d1528457a9e752812/src/Observer/Shop.cs#L27-L35
What's more, it doesn't really matter to subscribers how every `IPublisher` implements notifications behind the scenes.
Shop.cs can do it in one method, other publisher can do it in another named method or in two methods.
It's an implementation detail. :)

**Comment by Trooper13** [comment]
So the answer is to remove `Notify` method from public interface and change it access modifier to `private` ?

**Comment by m-wilczynski** [comment]
You're the one to decide. :)

**Comment by m-wilczynski** [comment]
Alright, I can see you've figured it out. Closing. 👍🏻
